processing_config:
  # Days
  despike_running_mean_dx : 3.0
  # Meters
  despike_running_mean_dy: 10.0
  # Percentage of whole data range to calculate statistics over
  data_range: 0.95
  # Removes/interpolates points greater then this from the mean (std dev)
  despike_deviations_for_mean: 2.0
  # max gap to interpolate over is less then this (meters)
  max_depth_gap: 50.0
  # True - do not include dives that are missing; False they are left as NaN profiles
  remove_missing_dives: true
  # Hack for SG219 (and maybe others) to mark the downcast a bad for the ocr504i
  ocr504i_hack: false
global_attributes:
  time_coverage_resolution: "PT1S"
  geospatial_vertical_units: "meter"
  geospatial_vertical_resolution: "meter"
  geospatial_vertical_positive: "no"
  platform: "glider"
  geospatial_lat_units: "degrees"
  geospatial_lat_resolution: "0.0001"
  geospatial_lon_units: "degrees"
  geospatial_lon_resolution: "0.0001"
  license: "These data may be redistributed and used without restriction."
  keywords_vocabulary: "NASA/GCMD Earth Science Keywords Version 6.0.0.0"
  Metadata_Conventions: "Unidata Dataset Discovery v1.0"
  Conventions: "CF-1.6,ACDD-1.3"
  standard_name_vocabulary: "CF-1.6"
  featureType: "trajectoryProfile"
  nodc_template_version: "NODC_NetCDF_Trajectory_Template_v0.9"
  processing_level: "L3"
  # Update
  institution: "Applied Physics Lab, University of Washington, Seattle, WA"
  # Update
  naming_authority: "edu.washington.apl"
  # Update
  creator_name: "Luc Rainville"
  # Update
  creator_url: "https://iop.apl.washington.edu"
  # Update
  creator_email: "lucrain@uw.edu"

