# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check In Actions

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install ruff
        if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi
    - name: Check with Ruff
      run: |
        ruff check --output-format=github
    #- name: Test with pytest
    #  run: |
    #    pytest --cov --cov-report term-missing tests/
